name: foodapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  google_fonts: ^5.1.0
  firebase_database: ^10.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/menu/
    - assets/images/salatalar/
    - assets/images/pizzalar/
    - assets/images/makarnalar/
    - assets/images/tatlilar/
    - assets/logo.png
  
flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

  uses-material-design: true